version: "3"
services:
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - 5000:5000
  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000